name: flagfall
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  auto_size_text: ^2.1.0
  eva_icons_flutter: 2.0.1
  flutter_native_splash: ^1.1.8+4
  get: ^4.2.5
  flutter_svg: ^0.22.0
  percent_indicator: ^3.0.1
  # provider: ^6.0.0
  provider: ^5.0.0
  # chess: ^0.7.0
  chess: ^0.6.6
  # flutter_chess_board: ^0.9.7
  firebase_core: ^1.6.0
  firebase_database: ^7.2.1
  cloud_firestore: ^2.5.1
  firebase_auth: ^3.1.0
  # image_downloader: ^0.30.0
  chess_vectors_flutter: ^1.0.12
  scoped_model: ^1.1.0
  flutter_launcher_icons: ^0.9.2


flutter_native_splash:  
  color: "#ffffff"
  image: assets/images/logo.png
  background: assets/images/background.jpg
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter  
  # flutter_launcher_icons: ^0.9.2
  
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: 
  assets:
    - assets/boards/chess_board.png
    - assets/boards/brown_board.png
    - assets/boards/2.0x/brown_board.png
    - assets/boards/3.0x/brown_board.png
    - assets/boards/orange_board.png
    - assets/boards/2.0x/orange_board.png
    - assets/boards/3.0x/orange_board.png
    - assets/boards/green_board.png
    - assets/boards/2.0x/green_board.png
    - assets/boards/3.0x/green_board.png
    - assets/boards/dark_brown_board.png
    - assets/boards/2.0x/dark_brown_board.png
    - assets/boards/3.0x/dark_brown_board.png
    - assets/boards/ss.png
    
    - assets\images\background.jpg
    - assets\images\MyDrawerBackground.png
    - assets\images\HomePageComponentTournament.png
    - assets\images\HomePageComponentRandom.png
    - assets\images\HomePageComponentSearch.png
    - assets\images\HomePageComponentBot.png
    - assets\images\FlagfallTheme.png
    - assets\images\DefaultTheme.png
    - assets\images\ClassicTheme.png
    - assets\images\logo.png
    - assets\images\ForeignProfileComponentChallenge.png
    - assets\images\ForeignProfileBackGround.png
    - assets\images\HistoryBackGround.png
    - assets\images\StoreBackGround.png
    - assets\images\StoreColorFlagFall.png
    - assets\images\StoreColorDefault.png
    - assets\images\StoreColorClassic.png
    - assets\images\StorePiecesFlagFall.png
    - assets\images\StorePiecesDefault.png
    - assets\images\StorePiecesClassic.png
    - assets\images\LobbiesBackground.png
    - assets\images\AnalysisBackGround.png
    - assets\images\AnalysisBoard.png
    - assets\images\GameBoard.png
    - assets\images\ChatBackGround.png
    - assets\images\HomePageComponentOfflineMatch.png
    - assets\Avatars\1.png
    - assets\Avatars\2.png
    - assets\Avatars\3.png
    - assets\Avatars\4.png
    - assets\Avatars\5.png
    - assets\Avatars\6.png
    - assets\Avatars\7.png
    - assets\Avatars\8.png
    - assets\Avatars\9.png
    - assets\Avatars\10.png
    - assets\Avatars\11.png
    - assets\Avatars\12.png
    - assets\Avatars\13.png
    - assets\Avatars\14.png
    - assets\Avatars\15.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
